#!/bin/bash

if [[ $1 ]]; then
	echo "Usage: $0" >&2
	exit 1
fi

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
	echo "Usage: $0"
	echo "Get your current public IP."
fi

echo "$(curl -s ifconfig.me)"

exit 0
