#!/bin/bash

if [[ -z $1 ]]; then
	echo "Usage: $0 [PIDS...]" >&2
	exit 1
fi
if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
	echo "Usage: $0 [PIDS...]"
	echo "Kill all the specified pids."
	exit 0
fi

for i in "$@"; do
	kill -s KILL "$i"
done
